<?php
print("1.General function <br/>");
include('app101.php');
print("<br/> 2.Anonymous functions <br/>");
include('app102.php');
print("<br/> 3.Passing an anonymous function to another function <br/>");
include('app103.php');
echo('<br/>');
print("<br/> 4.Return anonymous function <br/>");
include('app104.php');
print("<br/> 5.Scope of the anonymous function <br/>");
include('app105.php');
print("<br/> 6.PHP Closutre <br/>");
include('app106.php');
print("<br/> 7.PHP Closutre <br/>");
include('app107.php');
print("<br/> 8.Arrow function <br/>");
include('app108.php');
print("<br/> 9.Arrow function <br/>");
include('app109.php');